
enum Skill {
	# Attributes
	STRENGTH, DEXTERITY, CONSTITUTION, INTELLIGENCE, WISDOM, CHARISMA,
	
	# Skills
	ACROBATICS, ARCANE, CRAFT, DIPLOMACY, DISABLE, DIVINE, FORTITUDE, 
	KNOWLEDGE, MELEE, PERCEPTION, RANGED, STEALTH, SURVIVAL
}
